### ISSUE TITLE
Consider adding ingredient and semantic clinical drug (see RXNORM) to drug_exposure_details

### ISSUE THREAD

**Issue by marc-outins** [outcomesinsights/generalized_data_model#100]
This works for CPRD and can be obtained from RXNORM.  Both variables entered as text fields.

**Comment by markdanese** [comment]
@marc-outins 
change generic_name to ingredient  (this is generic name / ingredient in Part D and drugsubstance in CPRD)
change brand_name to drug_name (this is brand name in Part D and productname in CPRD)

**Comment by markdanese** [comment]
maybe ingredient_source_value and drug_name_source value?

**Comment by marc-outins** [comment]
Closed by a21fc13fb3ed122073f206b9734b88b9bfa15a75
