### ISSUE TITLE
Divide the cost table into two parts

### ISSUE THREAD

**Issue by markdanese** [outcomesinsights/generalized_data_model#104]
The first table will be **payer_reimbursements** and the second will be called **costs**.

**Payer_reimbursements** will contain all of the columns from the current cost table except total_cost and total_cost_concept_id.  
 - We will add clinical_code_id to the table to support a possible future use case where we need to have costs for multiple items sharing the same context.  We should describe this as "optional" for now, but having a placeholder for it allows people with the use case to adopt it easily.  
 - The purpose of this table is to capture all costs reported in the course of paying for services.  It is designed from a US administrative claims data perspective.

The **costs** table will contain context_id, clinical_code_id, patient_id, currency_concept_id, cost_base, value and value_concept_id.  For the costs table, this will be an EAV-style table where the value_concept_id will define the type of economic information in the value field.  Context records could have multiple rows attached to them.  
 - As above, clinical_code_id is "optional" for now.  The use case is stronger in this table, because it allows users to put costs into EHR data at the level of the clinical code.  This may not be necessary, but having it here to help solve future use cases will be helpful.  
 - Cost_base is there to define the basis for the cost in the table (e.g., 2013 for a specific cost-to-charge ratio, or a specific cost from an external cost. 
 - We will probably need value_concept_ids for things like cost-to-charge ratio, calculated cost (for situations where the ETL process calculates a cost based on the available data), reported cost (where the ETL process imputes a cost from another source), and some other things that may become apparent with more use cases.

**Comment by marc-outins** [comment]
Closed by commits c222a46, e704fef, 362d35b, and 62037ff
