### ISSUE TITLE
Add SES data from SEER Medicare

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/generalized_data_model#123]
Originally from MarksJigsawIssues.xlsx

We need a way to add SES - socioeconomic - information from SEER Medicare.  Possibly add a table since some of this information can have related dates.

Tagging all for discussion.

**Comment by markdanese** [comment]
This is an important one to fix, so it should be a high priority.  The main issue is that some data sources (most) will treat patient characteristics as fixed.  Others will have multiple values per person over time.  So, it would be good to allow dates to be present or not, depending on the data source (and also multiple values per person).  The trick will be figuring out how to incorporate dates or to allow missing dates.

**Comment by marc-outins** [comment]
We can just add start and end dates to patient_details and allow missing for both.  Or we can make start date required and use birth date if there is no date and then allow end date to be null.

**Comment by markdanese** [comment]
We probably also need to figure out how the protocol builder will be used to bring in the information we need.  Particularly with regard to how it works with maximum lookback settings.

**Comment by marc-outins** [comment]
seer_2018_breast_xgeva_za on titan now has the updated patient_details table which now has the following columns:

id
patient_id
start_date
end_date
value_as_number
value_as_string
value_as_concept_id
patient_detail_concept_id
patient_detail_source_value
patient_detail_vocabulary_id

**Comment by jenniferduryea** [comment]
@marc-outins is this done?  Looks like specs were updated under https://github.com/outcomesinsights/generalized_data_model.  If so, please close ticket.

**Comment by marc-outins** [comment]
@jenniferduryea  this is ready to test in the dataset seer_2018_breast_xgeva_za on titan.  I still need to update gdm_250_extended to include patient_detail records

**Comment by jenniferduryea** [comment]
confirmed gdm data is using patient_details table and have start_dates and end_dates.  All values have a date assigned to them.  Current standard is to assign the patient's birthdate to the patient_details.start_date for "timeless" variables (such as sex, race, etc).  All other variables are assigned a date as to the date of the data cut (start) that the data is referenced.  In particular, vocabulary GDM_CENSUS_TRACT_MEASURE will have multiple values at each year (if applicable to the patient).  Looks good.
