### ISSUE TITLE
add number_per_day to drug table

### ISSUE THREAD

**Issue by markdanese** [outcomesinsights/generalized_data_model#93]
Days supplied is most commonly used in research, but the raw data might not include this information explicitly.  CPRD includes ndd which is the numeric daily dose, which is the number of items to be used each day.  Hence, if quantity is 60 and ndd is 2 then the days supplied is 30.  CPRD does not report days supplied.

**Comment by marc-outins** [comment]
Closed by 1640f86bdb7f036b7608d53c940a1184ffb4208a
