### ISSUE TITLE
consider ways of including time or duration for collection records

### ISSUE THREAD

**Issue by markdanese** [outcomesinsights/generalized_data_model#95]
CPRD has a consultation (visit) duration.  This could be handled using a datetime variable so that the start and end times represent the duration.  It could also be handled with explicit time variables or a duration variable.

The use case is that costing studies in the UK can use this variable to estimate the cost of a visit.

**Comment by marc-outins** [comment]
Move admission_details.los into collections and rename duration and add duration_unit_concept_id (days, hours, minutes, etc.)

**Comment by marc-outins** [comment]
Closed by 9c28213ae84123da32c880ef83b0b98d3606ea49
