### ISSUE TITLE
consider adding route to drug exposure details

### ISSUE THREAD

**Issue by markdanese** [outcomesinsights/generalized_data_model#96]
Route (oral, intravenous, rectal, etc) is commonly used and could be added to drug table.  should check OMOP v 5.1 to see what they are doing.

**Comment by markdanese** [comment]
route is available in CPRD.

**Comment by marc-outins** [comment]
Add route_concept_id to drug_exposure_details

**Comment by marc-outins** [comment]
Closed by 0fde1470c69268eeadfb5336d940771aa80e4ef0
