### ISSUE TITLE
consider changing brand_name and generic_name fields

### ISSUE THREAD

**Issue by markdanese** [outcomesinsights/generalized_data_model#97]
These are generally going to require a mapping to RxNorm to identify.  Part D data only uses NDC codes and there is no text fields.  CPRD has drug substance (ingredient, like Furosemide) and product name (which is the fully qualified name like Furosemide 40mg tablets).  These are also RxNorm ideas, so it may be better to use these in place of brand and generic.  We may need to look at some other drug data to finalize this.

**Comment by marc-outins** [comment]
Found use case in seer medicare part d, so keep it in.
